title: Rylie Y. Wieseler
email: rywqzv@umsystem.edu
address: E004 Locust Street Bldg., 615 Locust Street, Columbia, MO 65201

# social links
# github_username:  jekyll
linkedin_username: Rylie Wieseler

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: auto

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - cv.md
 - teaching.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
